"""add notification sent flag

Revision ID: 236117eca3ae
Revises: bce127d51fa0
Create Date: 2026-06-21 21:22:12.743374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236117eca3ae'
down_revision: Union[str, Sequence[str], None] = 'bce127d51fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'notification_sent')
    # ### end Alembic commands ###
